if (model == pointer_null)
{
    draw_self()
    return;
}
var prev_ztestebnabal = gpu_get_ztestenable()
var prev_writeablae = gpu_get_zwriteenable()
gpu_set_ztestenable(1)
gpu_set_zwriteenable(1)
if (!surface_exists(radix_surface))
    radix_surface = surface_create_fix(256, 256)
surface_set_target(radix_surface)
draw_clear_alpha(c_white, 0)
shader_set_fix(shd_passthrough)
var matrix = matrix_build(128, 128, depth, xAngle, yAngle, zAngle, xScale, (-yScale), zScale)
matrix_set(2, matrix)
vertex_submit(model, 4, (texture == pointer_null ? -1 : sprite_get_texture(texture, 0)))
surface_reset_target()
matrix_set(2, matrix_build_identity())
shader_reset()
gpu_set_ztestenable(prev_ztestebnabal)
gpu_set_zwriteenable(prev_writeablae)
if surface_exists(radix_surface)
    draw_surface(radix_surface, (x - 128), (y - 128))
