draw_rectangle_color(0, 0, obj_screensizer.actual_width, obj_screensizer.actual_height, c_black, c_black, c_black, c_black, 0)
draw_sprite(gerome_spr, gerome_index, gerome_x, gerome_y)
draw_sprite(spr_elevatorcliff, cliff_index, cliff_x, cliff_y)
shader_set_fix(shd_pal_swapper)
pal_swap_player_palette(spr_peppinoelevator, peppino_index, 1, 1)
draw_sprite(spr_peppinoelevator, peppino_index, peppino_x, peppino_y)
pal_swap_reset()
for (var i = 0; i < 10; i++)
    draw_sprite(spr_elevatorrope, 0, peppino_x, (peppino_y - (sprite_get_height(spr_elevatorrope) * i)))
