image_speed = 0.1
chose = 0
message = ""
showtext = 0
tvprompts_list = ds_list_create()
state = states.normal
promptxstart = 641
promptx = promptxstart
prompt = ""
promptspd = 1
prompt_buffer = 0
prompt_max = 150
promptsurface = -1
visualcombo = 0
tv_bg_index = 0
tv_trans = 0
tv_cooldown = 0
tv_x = (obj_screensizer.actual_width - 115)
tv_y = 80
targetgolf = -4
special_prompts = -4
hud_posx = 0
hud_posY = 0
combo_state = 0
combo_posX = 0
combo_vsp = 0
combo_posY = 0
combofill_x = 0
combofill_y = 0
combofill_index = 0
noisemax = 6
noisebuffer = noisemax
expressionsprite = -4
expressionbuffer = 0
golfsurf = -4
tvsprite = spr_tv_idle
sprite_index = spr_tv_off
bubbleindex = 0
bubblespr = -4
idleanim = 180
noisesprite = spr_noiseHUD_idle
xi = 500
yi = 600
imageindexstore = 0
once = 0
global.hurtcounter = 0
global.hurtmilestone = 3
alpha = 1
shownrankp = 0
shownranks = 0
shownranka = 0
shownrankb = 0
shownrankc = 0
collect_shake = 0
global.srank = 0
global.arank = 0
global.brank = 0
global.crank = 0
character = "PEPPINO"
chunkmax = 0
timer_xplus = -153
timer_yplus = -76
timer_xstart = ((obj_screensizer.actual_width / 2) + timer_xplus)
timer_ystart = (obj_screensizer.actual_height + timer_yplus)
timer_x = timer_xstart
timer_y = (timer_ystart + 212)
timer_tower = 0
pizzaface_sprite = spr_timer_pizzaface1
pizzaface_index = 0
johnface_sprite = spr_timer_johnface
johnface_index = 0
hand_sprite = spr_timer_hand1
hand_index = 0
barfill_x = 0
showtime_buffer = 0
tv_bg = 
{
    surf: -4,
    sprite: spr_gate_entranceBG,
    parallax: [0.65, 0.75, 0.85],
    x: 0,
    y: 0
}

lapflag_index = 0
targetspr = spr_tv_off
targetspr_old = spr_tv_off
propeller_index = 0
hand_x = 0
hand_y = 0
fill_lerp = 0
lap_x = timer_x
lap_y = (obj_screensizer.actual_height + 212)
sugarylevel = 0
bolevel = 0
tvreset = 0
jumpscare = -1
jumpscareimage = irandom((sprite_get_number(spr_scares) - 1))
jumpscaretext = 0
manualhide = 0
