shader_set_fix(shd_pal_swapper)
pal_swap_set(spr_peppalette, 1, 0)
draw_sprite_ext(sprite_index, -1, x, y, xscale, 1, 0, c_white, 1)
shader_reset()
draw_set_font(gml_Script_lang_get_font("font_small"))
draw_set_align(1)
draw_set_colour(c_white)
var yy = clamp(((sprite_get_bbox_top(sprite_index) + y) - 75), 0, (room_height - 16))
draw_text(x, yy, name)
draw_set_align()
