if (instance_number(object_index) > 1)
{
    instance_destroy()
    return;
}
global.current_level = -4
soundinit = 0
function player_destroy_sounds@gml_Object_obj_player_Create_0() //gml_Script_player_destroy_sounds@gml_Object_obj_player_Create_0
{
    if (!soundinit)
        return;
    destroy_sounds([snd_voiceok, snd_voicetransfo, snd_voiceouttransfo, snd_voicehurt, global.snd_fireass, global.snd_parry, global.snd_supertaunt, machsnd, jumpsnd, machrollsnd, weeniebumpsnd, knightslidesnd, gravecorpsesnd, barrelslidesnd, barrelbumpsnd, waterslidesnd, mrpinchsnd, hamkuffsnd, ratmountmachsnd, ratmountballsnd, ratmountgroundpoundsnd, ratmountpunchsnd, cheeseballsnd, boxxedspinsnd, pizzapeppersnd, ratdeflatesnd, ghostspeedsnd, freefallsnd, rollgetupsnd, tumblesnd, snd_uppercut, snd_dive, snd_crouchslide, snd_dashpad, animatronicsnd, burpsnd, superjumpsnd, suplexdashsnd, gallopingsnd, flippingsnd, snd_jetpackloop, sjumpcancelsnd, spindashsnd, global.snd_rank])
}

function player_init_sounds@gml_Object_obj_player_Create_0() //gml_Script_player_init_sounds@gml_Object_obj_player_Create_0
{
    soundinit = 1
    if (character == "SP")
    {
        global.snd_collect = "event:/modded/sfx/collectSP"
        global.snd_collectpizza = "event:/modded/sfx/collectSP"
        global.snd_collectgiantpizza = "event:/modded/sfx/collectgiantpizzaSP"
    }
    else
    {
        global.snd_collect = "event:/sfx/misc/collect"
        global.snd_collectpizza = "event:/sfx/misc/collectpizza"
        global.snd_collectgiantpizza = "event:/sfx/misc/collectgiantpizza"
    }
    if (character == "P")
    {
        snd_voiceok = fmod_event_create_instance((isgustavo ? "event:/sfx/voice/gusok" : "event:/sfx/voice/ok"))
        snd_voicetransfo = fmod_event_create_instance("event:/sfx/voice/transfo")
        snd_voiceouttransfo = fmod_event_create_instance("event:/sfx/voice/outtransfo")
        snd_voicehurt = fmod_event_create_instance((isgustavo ? "event:/sfx/voice/gushurt" : "event:/sfx/voice/hurt"))
        snd_voicemyea = "event:/sfx/voice/myea"
    }
    else if (character == "SP")
    {
        snd_voiceok = fmod_event_create_instance("event:/modded/sfx/voice/okSP")
        snd_voicetransfo = fmod_event_create_instance("event:/modded/sfx/voice/transfoSP")
        snd_voiceouttransfo = fmod_event_create_instance("event:/modded/sfx/voice/outtransfoSP")
        snd_voicehurt = fmod_event_create_instance("event:/modded/sfx/voice/hurtSP")
        snd_voicemyea = "event:/modded/sfx/voice/myeaSP"
    }
    else if (character == "N")
    {
        snd_voiceok = fmod_event_create_instance("event:/sfx/voice/noisepositive")
        snd_voicetransfo = fmod_event_create_instance("event:/sfx/voice/noisenegative")
        snd_voiceouttransfo = fmod_event_create_instance("event:/sfx/voice/noisepositive")
        snd_voicehurt = fmod_event_create_instance("event:/sfx/voice/noisenegative")
        snd_voicemyea = "event:/nosound"
    }
    else if (character == "V")
    {
        snd_voiceok = fmod_event_create_instance("event:/sfx/voice/vigiduel")
        snd_voicetransfo = fmod_event_create_instance("event:/sfx/voice/vigiangry")
        snd_voiceouttransfo = fmod_event_create_instance("event:/sfx/voice/vigiduel")
        snd_voicehurt = fmod_event_create_instance("event:/sfx/voice/vigiduel")
        snd_voicemyea = "event:/nosound"
    }
    else
    {
        snd_voiceok = fmod_event_create_instance("event:/nosound")
        snd_voicetransfo = fmod_event_create_instance("event:/nosound")
        snd_voiceouttransfo = fmod_event_create_instance("event:/nosound")
        snd_voicehurt = fmod_event_create_instance("event:/nosound")
        snd_voicemyea = "event:/nosound"
    }
    if (character == "P")
        global.snd_fireass = fmod_event_create_instance("event:/sfx/pep/fireassP")
    else if (character == "SP")
        global.snd_fireass = fmod_event_create_instance("event:/sfx/pep/fireassSP")
    else if (character == "N")
        global.snd_fireass = fmod_event_create_instance("event:/sfx/pep/fireassN")
    else
        global.snd_fireass = fmod_event_create_instance("event:/sfx/pep/fireass")
    if (character == "SP" || character == "SN")
        global.snd_parry = fmod_event_create_instance("event:/modded/sfx/parrySP")
    else
        global.snd_parry = fmod_event_create_instance("event:/sfx/pep/parry")
    if (character == "BN")
        global.snd_supertaunt = fmod_event_create_instance("event:/modded/sfx/supertauntBN")
    else if (character == "SP" || character == "SN")
        global.snd_supertaunt = fmod_event_create_instance("event:/modded/sfx/pizzysupertaunt")
    else
        global.snd_supertaunt = fmod_event_create_instance("event:/sfx/pep/supertaunt")
    if (character == "SP" || character == "SN")
        global.snd_rank = fmod_event_create_instance("event:/music/rankSP")
    else if (character == "BN")
        global.snd_rank = fmod_event_create_instance("event:/music/rankBN")
    else
        global.snd_rank = fmod_event_create_instance("event:/music/rank")
    if (character == "SP" || character == "SN")
        global.snd_collecttoppin = "event:/modded/sfx/collecttoppinSP"
    else
        global.snd_collecttoppin = "event:/sfx/misc/collecttoppin"
    if (character == "P")
        global.snd_screamboss = "event:/sfx/pep/screamboss"
    else if (character == "N")
        global.snd_screamboss = "event:/sfx/voice/noisescream"
    else
        global.snd_screamboss = "event:/modded/sfx/enemyscream"
    machsnd = fmod_event_create_instance("event:/sfx/pep/mach")
    jumpsnd = fmod_event_create_instance("event:/sfx/pep/jump")
    machrollsnd = fmod_event_create_instance("event:/sfx/pep/machroll")
    weeniebumpsnd = fmod_event_create_instance("event:/sfx/weenie/bump")
    knightslidesnd = fmod_event_create_instance("event:/sfx/knight/slide")
    gravecorpsesnd = fmod_event_create_instance("event:/sfx/pep/gravecorpse")
    barrelslidesnd = fmod_event_create_instance("event:/sfx/barrel/slide")
    barrelbumpsnd = fmod_event_create_instance("event:/sfx/barrel/bump")
    waterslidesnd = fmod_event_create_instance("event:/sfx/misc/waterslide")
    mrpinchsnd = fmod_event_create_instance("event:/sfx/misc/mrpinch")
    hamkuffsnd = fmod_event_create_instance("event:/sfx/misc/hamkuff")
    ratmountmachsnd = fmod_event_create_instance("event:/sfx/ratmount/mach")
    ratmountballsnd = fmod_event_create_instance("event:/sfx/ratmount/ball")
    ratmountgroundpoundsnd = fmod_event_create_instance("event:/sfx/ratmount/groundpound")
    ratmountpunchsnd = fmod_event_create_instance("event:/sfx/ratmount/punch")
    cheeseballsnd = fmod_event_create_instance("event:/sfx/cheese/ball")
    boxxedspinsnd = fmod_event_create_instance("event:/sfx/boxxed/spin")
    pizzapeppersnd = fmod_event_create_instance("event:/sfx/pep/pizzapepper")
    ratdeflatesnd = fmod_event_create_instance("event:/sfx/rat/deflate")
    ghostspeedsnd = fmod_event_create_instance("event:/sfx/pep/ghostspeed")
    freefallsnd = fmod_event_create_instance("event:/sfx/pep/freefall")
    rollgetupsnd = fmod_event_create_instance("event:/sfx/pep/rollgetup")
    tumblesnd = fmod_event_create_instance("event:/sfx/pep/tumble")
    snd_uppercut = fmod_event_create_instance("event:/sfx/pep/uppercut")
    snd_dive = fmod_event_create_instance("event:/sfx/pep/dive")
    snd_crouchslide = fmod_event_create_instance("event:/sfx/pep/crouchslide")
    snd_dashpad = fmod_event_create_instance("event:/sfx/misc/dashpad")
    animatronicsnd = fmod_event_create_instance("event:/sfx/pep/animatronic")
    burpsnd = fmod_event_create_instance("event:/sfx/enemies/burp")
    superjumpsnd = fmod_event_create_instance("event:/sfx/pep/superjump")
    suplexdashsnd = fmod_event_create_instance("event:/sfx/pep/suplexdash")
    gallopingsnd = fmod_event_create_instance("event:/sfx/misc/galloping")
    flippingsnd = fmod_event_create_instance("event:/modded/sfx/pizzyflip")
    snd_jetpackloop = fmod_event_create_instance("event:/sfx/noise/jetpackloop")
    sjumpcancelsnd = fmod_event_create_instance("event:/sfx/pep/superjumpcancel")
    spindashsnd = fmod_event_create_instance("event:/modded/sfx/snick/spindashrev")
}

init_collision()
global.throwarc = 1
global.hidetiles = 0
global.leveltosave = -4
global.leveltorestart = -4
global.hub_bgsprite = -4
global.offload_tex = -4
global.bossplayerhurt = 0
global.boss_invincible = 0
global.highest_combo = 0
global.player_damage = 0
global.peppino_damage = 0
global.gustavo_damage = 0
global.enemykilled = 0
global.johnresurrection = 0
global.startgate = 0
global.bossintro = 0
global.palettetexture = -4
global.palettesurface = -4
global.palettesurfaceclip = -4
global.levelattempts = 0
global.exitrank = 0
global.playerhit = 0
global.door_sprite = spr_door
global.door_index = 0
global.pistol = 0
lastroom_soundtest = room
lastroom_secretportalID = -4
dropboost = 0
global.snd_escaperumble = fmod_event_create_instance("event:/sfx/misc/escaperumble")
global.snd_johndead = fmod_event_create_instance("event:/sfx/enemies/johndead")
global.snd_spaceship = fmod_event_create_instance("event:/sfx/misc/spaceship")
global.snd_fakesanta = fmod_event_create_instance("event:/sfx/enemies/fakesanta")
global.snd_rankup = fmod_event_create_instance("event:/sfx/ui/rankup")
global.snd_pizzafacemoving = fmod_event_create_instance("event:/sfx/pizzaface/moving")
global.snd_rankdown = fmod_event_create_instance("event:/sfx/ui/rankdown")
global.snd_breakblock = fmod_event_create_instance("event:/sfx/misc/breakblock")
global.snd_bellcollect = fmod_event_create_instance("event:/sfx/misc/bellcollect")
global.snd_cardflip = fmod_event_create_instance("event:/sfx/misc/cardflip")
global.snd_explosion = fmod_event_create_instance("event:/sfx/misc/explosion")
global.snd_cheesejump = fmod_event_create_instance("event:/sfx/pep/cheesejump")
global.snd_ventilator = fmod_event_create_instance("event:/sfx/misc/ventilator")
global.snd_trashjump1 = fmod_event_create_instance("event:/sfx/misc/trashjump1")
global.snd_thunder = fmod_event_create_instance("event:/sfx/knight/thunder")
global.snd_captaingoblinshoot = fmod_event_create_instance("event:/sfx/misc/captaingoblinshoot")
global.snd_golfjingle = fmod_event_create_instance("event:/sfx/misc/golfjingle")
global.snd_mrstickhat = fmod_event_create_instance("event:/sfx/misc/mrstickhat")
global.snd_alarm = fmod_event_create_instance("event:/sfx/enemies/alarm")
global.snd_slidersfx = fmod_event_create_instance("event:/sfx/ui/slidersfx")
global.snd_slidermusic = fmod_event_create_instance("event:/sfx/ui/slidermusic")
global.snd_slidermaster = fmod_event_create_instance("event:/sfx/ui/slidersfxmaster")
global.snd_bossbeaten = fmod_event_create_instance("event:/sfx/misc/bossbeaten")
global.snd_secretwall = fmod_event_create_instance("event:/modded/sfx/secretwall")
uncrouch = 0
parryID = -4
bodyslam_notif = 0
swingdingthrow = 0
sjumptimer = 0
can_jump = 0
coyote_time = 0
invtime = 0
parry_lethal = 0
usepalette = 1
jetpackeffect = 0
superchargebuffer = 0
fireasseffect = 0
pistolanim = -4
pistolindex = 0
pistolcooldown = 0
pistolchargesound = 0
policetaxi = 0
collision_flags = 0
breakdance_pressed = 0
restartbuffer = 0
jetpackdash = 0
flamecloud_buffer = 0
rankpos_x = x
rankpos_y = y
transformationlives = 0
punch_afterimage = 0
superchargecombo_buffer = -1
superattackstate = states.normal
afterimagedebris_buffer = 0
scale_xs = 1
scale_ys = 1
verticalbuffer = 0
verticalstate = states.normal
webID = -4
float = 0
boxxedpepjump = 10
boxxedpepjumpmax = 10
icemovespeed = 0
prevmove = 0
prevhsp = 0
prevstate = states.normal
prevxscale = 1
prevsprite = sprite_index
move = 0
prevmovespeed = 0
previcemovespeed = 0
icedir = 1
icemomentum = 0
savedicedir = 1
isgustavo = 0
jumped = 1
rocketvsp = 0
sticking = 0
xscale = 1
yscale = 1
facehurt = 0
steppy = 0
steppybuffer = 0
depth = -7
movespeed = 19
jumpstop = 0
ramp = 0
ramp_points = 0
bombup_dir = 1
knightmomentum = 0
grabbingenemy = 0
blur_effect = 0
firemouth_dir = 1
firemouth_max = 10
firemouth_buffer = firemouth_max
firemouth_afterimage = 0
cow_buffer = 0
balloonbuffer = 0
shoot_buffer = 0
shoot_max = 20
dynamite_inst = -4
golfid = -4
bombgrabID = -4
barrelslope = 0
barrel_maxmovespeed = 16
barrel_maxfootspeed = 10
barrel_rollspeed_threshold = 10
barrel_accel = 1
barrel_deccel = 1
barrel_slopeaccel = 0.25
barrel_slopedeccel = 0.5
barrelroll_slopeaccel = 0.5
barrelroll_slopedeccel = 0.35
hurt_buffer = -1
hurt_max = 120
invhurt_buffer = 0
invhurt_max = 30
ratmount_movespeed = 8
ratmount_fallingspeed = 0
ratgrabbedID = -4
ratpowerup = -4
ratshootbuffer = 0
rateaten = 0
gustavodash = 0
brick = 0
ratmountpunchtimer = 25
gustavokicktimer = 5
cheesepep_buffer = 0
cheesepep_max = 10
pepperman_accel = 0.25
pepperman_deccel = 0.5
pepperman_accel_air = 0.15
pepperman_deccel_air = 0.25
pepperman_maxhsp_normal = 6
pepperman_jumpspeed = 11
pepperman_grabID = -4
shoulderbash_mspeed_start = 12
shoulderbash_mspeed_loop = 10
shoulderbash_jumpspeed = 11
visible = true
state = states.titlescreen
jumpAnim = 1
landAnim = 0
machslideAnim = 0
moveAnim = 1
stopAnim = 1
crouchslideAnim = 1
crouchAnim = 1
machhitAnim = 0
stompAnim = 0
inv_frames = 0
hurted = 0
autodash = 0
mach2 = 0
stop_buffer = 8
slope_buffer = 8
stop_max = 16
parry = 0
parry_inst = -4
taunt_to_parry_max = 8
parrytimer = 0
parry_count = 0
parry_max = 8
is_firing = 0
input_buffer_jump = 0
input_buffer_down = 0
input_buffer_mach = 0
input_buffer_jump_negative = 0
input_buffer_shoot = 0
input_buffer_secondjump = 8
input_buffer_highjump = 8
input_buffer_walljump = 0
input_buffer_slap = 0
input_attack_buffer = 0
input_finisher_buffer = 0
input_up_buffer = 0
input_down_buffer = 0
hit_connected = 0
player_x = x
player_y = y
targetRoom = tower_entrancehall
targetDoor = "A"
scr_init_input()
flash = 0
key_particles = 0
barrel = 0
bounce = 0
a = 0
idle = 0
attacking = 0
slamming = 0
superslam = 0
grinding = 0
machpunchAnim = 0
punch = 0
machfreefall = 0
shoot = 0
instakillmove = 0
stunmove = 0
windingAnim = 0
facestompAnim = 0
ladderbuffer = 0
toomuchalarm1 = 0
toomuchalarm2 = 0
idleanim = 0
momemtum = 0
cutscene = 0
grabbing = 0
dir = xscale
shotgunAnim = 0
goingdownslope = 0
goingupslope = 0
fallinganimation = 0
bombpeptimer = 100
suplexmove = 0
suplexhavetomash = 0
anger = 0
angry = 0
baddiegrabbedID = -4
spr_palette = spr_peppalette
character = "P"
scr_characterspr()
paletteselect = 1
colorchange = 0
treasure_x = 0
treasure_y = 0
treasure_room = 0
wallspeed = 0
tauntstoredstate = states.normal
tauntstoredmovespeed = 6
tauntstoredsprite = spr_player_idle
taunttimer = 20
tauntstoredvsp = 0
tauntstoredisgustavo = 0
tube_id = -1
backtohubstartx = x
backtohubstarty = y
backtohubroom = Mainmenu
slapcharge = 0
slaphand = 1
slapbuffer = 8
slapflash = 0
freefallsmash = 0
costumercutscenetimer = 0
heavy = 0
lastroom_x = 0
lastroom_y = 0
lastroom = 0
lastTargetoor = "A"
hallway = 0
savedhallway = 0
hallwaydirection = 0
savedhallwaydirection = 0
vhallwaydirection = 0
savedvhallwaydirection = 0
verticalhallway = 0
savedverticalhallway = 0
vertical_x = x
verticalhall_vsp = 0
box = 0
roomstartx = 0
roomstarty = 0
swingdingbuffer = 0
swingdingdash = 0
lastmove = 0
backupweapon = 0
stickpressed = 0
spotlight = 1
macheffect = 0
chargeeffectid = obj_null
dashcloudid = obj_null
crazyruneffectid = obj_null
fightball = 0
superslameffectid = obj_null
speedlineseffectid = obj_null
angryeffectid = obj_null
thrown = 0
transformationsnd = 0
mach1snd = -1
mach2snd = -1
mach3snd = -1
knightslide = -1
bombpep1snd = -1
mach4snd = -1
tumble2snd = -1
tumble1snd = -1
tumble3snd = -1
tumbleintro = 0
rocketsnd = -1
hamkuffID = -4
superjumpholdsnd = -1
superjumpprepsnd = -1
pogospeed = 2
pogocharge = 100
pogochargeactive = 0
wallclingcooldown = 10
bombcharge = 0
flashflicker = 0
flashflickertime = 0
kickbomb = 0
doublejump = 0
pogospeedprev = 0
fightballadvantage = 0
coopdelay = 0
supercharged = 0
superchargedeffectid = obj_null
used_supercharge = 0
pizzashield = 0
pizzashieldid = obj_null
pizzapepper = 0
transformation[0] = (51 << 0)
transformation[1] = (47 << 0)
transformation[2] = (38 << 0)
transformation[3] = (33 << 0)
transformation[4] = (21 << 0)
transformation[5] = (24 << 0)
transformation[6] = (25 << 0)
transformation[7] = (30 << 0)
transformation[8] = (29 << 0)
transformation[9] = (10 << 0)
transformation[10] = (9 << 0)
transformation[11] = (59 << 0)
transformation[12] = (31 << 0)
transformation[13] = (89 << 0)
transformation[14] = (112 << 0)
transformation[15] = (16 << 0)
transformation[16] = (17 << 0)
transformation[17] = (11 << 0)
transformation[18] = (150 << 0)
transformation[19] = (146 << 0)
transformation[20] = (184 << 0)
transformation[21] = (186 << 0)
transformation[22] = (52 << 0)
transformation[23] = (53 << 0)
transformation[24] = (54 << 0)
transformation[25] = (116 << 0)
transformation[26] = (114 << 0)
transformation[27] = (113 << 0)
transformation[28] = (22 << 0)
transformation[29] = (32 << 0)
transformation[30] = (49 << 0)
transformation[31] = (48 << 0)
transformation[32] = (13 << 0)
transformation[33] = (14 << 0)
transformation[34] = (12 << 0)
transformation[35] = (35 << 0)
transformation[36] = (34 << 0)
transformation[37] = (185 << 0)
transformation[38] = (26 << 0)
transformation[39] = (31 << 0)
transformation[40] = (115 << 0)
transformation[41] = (304 << 0)
transformation[42] = (305 << 0)
transformation[43] = (306 << 0)
transformation[44] = (310 << 0)
transformation[45] = (311 << 0)
transformation[46] = (312 << 0)
transformation[47] = (313 << 0)
keysound = 0
c = 0
stallblock = 0
breakdance = 50
skateboarding = 0
hitX = x
hitY = y
hithsp = 0
hitvsp = 0
hitstunned = 0
hitxscale = 1
stunned = 0
hitLag = 25
supercharge = 0
mort = 0
sjumpvsp = -12
freefallvsp = 15
hitlist = ds_list_create()
animlist = ds_list_create()
lungeattackID = -4
lunge_hits = 0
lunge_hit_buffer = 0
lunge_buffer = 0
finisher = 0
finisher_buffer = 0
finisher_hits = 0
uplaunch = 0
downlaunch = 0
dash_doubletap = 0
finishingblow = 0
launch = 0
launched = 1
launch_buffer = 0
jetpackfuel = 0
jetpackmax = 200
walljumpbuffer = 0
farmerpos = 0
clowntimer = 0
knightmiddairstop = 0
knightmove = -1
if (!variable_global_exists("saveroom"))
{
    global.combodropped = 0
    global.saveroom = ds_list_create()
    global.escaperoom = ds_list_create()
    global.lap = 0
    global.laps = 0
    global.playerhealth = 100
    global.instancelist = ds_list_create()
    global.followerlist = ds_list_create()
    global.maxrailspeed = 2
    global.railspeed = global.maxrailspeed
    global.levelreset = 0
    global.temperature = 0
    global.temperature_spd = 0.01
    global.temp_thresholdnumber = 5
    global.use_temperature = 0
    global.timedgatetimer = 0
    global.timedgatetime = 0
    global.timedgateid = -4
    global.timedgatetimemax = 0
    global.key_inv = 0
    global.shroomfollow = 0
    global.cheesefollow = 0
    global.tomatofollow = 0
    global.sausagefollow = 0
    global.pineapplefollow = 0
    global.pepanimatronic = 0
    global.keyget = 0
    global.collect = 0
    global.collectN = 0
    global.hats = 0
    global.extrahats = 0
    global.treasure = 0
    global.combo = 0
    global.previouscombo = 0
    global.combotime = 0
    global.combotimepause = 0
    global.prank_enemykilled = 0
    global.prank_cankillenemy = 1
    global.tauntcount = 0
    global.comboscore = 0
    global.savedcomboscore = 0
    global.savedcombo = 0
    global.heattime = 0
    global.pizzacoin = 0
    global.toppintotal = 1
    global.hit = 0
    global.baddieroom = ds_list_create()
    global.hp = 2
    global.gotshotgun = 0
    global.showgnomelist = 1
    global.panic = 0
    global.snickchallenge = 0
    global.golfhit = 0
    global.style = -1
    global.secretfound = 0
    global.shotgunammo = 0
    global.monsterspeed = 0
    global.monsterlives = 3
    global.giantkey = 0
    global.coop = 0
    global.baddiespeed = 1
    global.baddiepowerup = 0
    global.baddierage = 0
    global.style = 0
    global.stylethreshold = 0
    global.pizzadelivery = 0
    global.failcutscene = 0
    global.pizzasdelivered = 0
    global.spaceblockswitch = 1
    global.gerome = 0
    global.pigtotal_add = 0
    global.bullet = 0
    global.fuel = 3
    global.ammorefill = 0
    global.ammoalt = 1
    global.mort = 0
    global.stylelock = 0
    global.pummeltest = 1
    global.horse = 0
    global.checkpoint_room = -4
    global.checkpoint_door = "A"
    global.kungfu = 0
    global.graffiticount = 0
    global.graffitimax = 20
    global.noisejetpack = 0
    global.hasfarmer = array_create(3, 0)
    global.savedattackstyle = -4
    global.snickrematch = 0
    global.checkpoint_data = -4
}
angle = 0
mach4mode = 0
railmomentum = 0
railmovespeed = 0
raildir = 1
boxxed = 0
boxxeddash = 0
boxxeddashbuffer = 0
cheesepeptimer = -1
cheeseballbounce = 0
slopejump = 0
slopejumpx = 0
hooked = 0
swingdingendcooldown = 0
crouchslipbuffer = 0
breakdance_speed = 0.25
notecreate = 50
jetpackbounce = 0
firemouthflames = 0
ghostdash = 0
ghostpepper = 0
ghosteffect = 0
ghostbump = 1
ghostbumpbuffer = -1
dashcloudtimer = 0
grabclimbbuffer = 0
gustavohitwall = 0
gusdashpadbuffer = 0
holycross = 0
knightdowncloud = 0
piledrivereffect = 0
fireasslock = 0
pistolcharge = 0
pistolcharged = 0
pistolchargebuffer = 0
pistolchargedelay = 5
pistolchargeshooting = 0
pistolchargeshot = 8
pistolchargeeffect = 0
gravesurfingjumpbuffer = 0
spinsndbuffer = 5
boxxedspinbuffer = 0
noisebossscream = 0
secretportalID = -4
smoothx = 0
oldHallway = 0
noisetype = 0
input_buffer_pistol = 0
input_buffer_grab = 0
keydoor = 0
pistol = 0
jetpackcancel = 0
suplexmove2 = 0
breakout = 0
shaketime = 0
hat = -1
pet = -1
pet_prev = -1
petID = -4
superjumped = 0
image_blend_func = -4
substate = states.normal
drillspeed = 0
cyop_backtohubroom = -4
cyop_backtohubx = 0
cyop_backtohuby = 0
gravityjump = 0
gravityangle = 0
ceilingrun = 0
custom_palette = 0
custom_palette_array = array_create(64)
