var p = (tex_max - array_length(tex_list))
var t = ((p / tex_max) * 100)
var tt = (p / tex_max)
var spr_w = sprite_get_width(spr_loadingscreen_cheesy)
var spr_h = sprite_get_height(spr_loadingscreen_cheesy)
var xx = floor(((obj_screensizer.actual_width / 2) - (spr_w / 2)))
var yy = floor(((obj_screensizer.actual_height / 2) - (spr_h / 2)))
draw_sprite_part_ext(spr_loadingscreen_cheesy, 0, (spr_w * tt), 0, spr_w, spr_h, (xx + (spr_w * tt)), yy, 1, 1, c_white, image_alpha)
draw_sprite_part_ext(spr_loadingscreen_cheesy, 1, 0, 0, (spr_w * tt), spr_h, xx, yy, 1, 1, c_white, image_alpha)
if (image_alpha < 1)
    return;
draw_healthbar(0, (obj_screensizer.actual_height - 6), obj_screensizer.actual_width, obj_screensizer.actual_height, t, c_black, c_white, c_white, 0, 0, 0)
draw_sprite_stretched_ext(spr_gradient, 0, 0, (obj_screensizer.actual_height - 16), ((p / tex_max) * obj_screensizer.actual_width), 10, c_black, 0.15)
draw_set_colour(c_white)
draw_set_font(gml_Script_lang_get_font("font_small"))
draw_set_align(0, 2)
draw_text(4, (obj_screensizer.actual_height - 8), string("{0} ({1}/{2})", text, p, tex_max))
draw_set_align()
